name = "whisper-transcribe-beta"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_als", "nodejs_compat"]

account_id = "b8b395a6029fc23bcc4f4ac31fcd1f1c"

routes = [
  { pattern = "beta.listen.silent.energy", custom_domain = true }
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[vars]
CORS_ORIGIN = "https://beta.listen.silent.energy"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "whisper-transcriptions"

[[d1_databases]]
binding = "DB"
database_name = "whisper-transcriptions"
database_id = "5cc56700-c514-4456-9dc9-8ca589753ac6"

[env.production]
name = "whisper-transcribe"

routes = [
  { pattern = "listen.silent.energy", custom_domain = true }
]

[env.production.vars]
CORS_ORIGIN = "https://listen.silent.energy"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "whisper-transcriptions"

[[env.production.d1_databases]]
binding = "DB"
database_name = "whisper-transcriptions"
database_id = "5cc56700-c514-4456-9dc9-8ca589753ac6"
